### PR TITLE
remove unnecessary files

### PR DESCRIPTION
**Pull request by NoelleDL**
### What

Make the correct Welsh words appear on search/hide search toggle

### How to review

Go to homepage on, switch to Welsh site and mobile view. See that when clicking "Chwilio", "Hide search" appears, clicking on "Hide search" makes "Search appear. 

Pull this branch. Click on "Chwilio", see that "Cuddio" (Hide search) appears. Click on "Cuddio" and "Chwilio" appears. 

### Who can review

Anyone but me.

### CODE REVIEW

**Review by justinpjose — COMMENTED** [review]
The concourse build has failed

**Comment by NoelleDL** [comment]
Hmm. Something strange happened when I went to rebase. I might need some help resolving this.

**Comment by dandwal** [comment]
> Hmm. Something strange happened when I went to rebase. I might need some help resolving this.

Hi, I just made a bug for this issue which has the fix in it:
https://trello.com/c/mIXUaCTh/1460-sixteens-is-broken-wont-build-on-docker-concourse

**Review by justinpjose — APPROVED** [review]
Looks good

**Pull request merged**
