### PR TITLE
Feature/chart builder

### PR DESCRIPTION
**Pull request by mcoulthurst**
What

Change display of charts and tables created by chartBuilder

How to review

Test chart builder in Florence and charts in Babbage

Who can review

Review by Carl Hemborough (Changes by Martin Coulthurst)

### CODE REVIEW

**Comment by Crispioso** [comment]
Think there's a few minor bits:
1. Looks like we possibly want to remove the 'view chart' button.
localhost-20000-economy-grossdomesticproductgdp-bulletins-grossdomesticproductpreliminaryestimate-aprtojune2016 iphone 5

2. I noticed we've removed the border on tables and charts on mobile but we still have the `padding-left:16px;`. Assume we probably want to remove it so that it doesn't look indented.

**Comment by mcoulthurst** [comment]
Have changed the padding-left in Sixteens- is the _view chart_ in Babbage? Have commented it out of mobile-chart.js

**Comment by Crispioso** [comment]
@mcoulthurst 
Yeah, it probably will be in Babbage. We'll just need to check that it's still showing for tables though, can't remember if they share the same function. 

I've also noticed that we don't have the grey border on charts on tablet or mobile, was this the plan?

**Comment by mcoulthurst** [comment]
Cheers - I've removed the button from mobilechart.js in Babbage.  wrt the grey border, that was my understanding.

**Pull request merged**
